[package]
name = "cho"
version = "0.3.0"
edition = "2024"
description = "A small, type-aware text processor for the command line"
license = "MIT"
repository = "https://github.com/k0f1sh/cho"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["std"] }
chrono-tz = "0.10.4"
csv = "1.3"
ipnet = "2.11"
regex = "1.11"
semver = "1.0"
url = "2.5"
