;;; cho-mode-data.el --- Generated Cho callable data -*- lexical-binding: t; -*-
;; Generated from metadata.json by generate-cho-mode-data.el.
;; Do not edit this file by hand.

(defconst cho-mode--metadata-version "0.36.0"
  "Cho version represented by the generated mode data.")

(defconst cho-mode--functions
  '("print" "p" "filter" "f" "field" "fields" "fields-from"
    "fields-to" "+" "-" "*" "/" "%" "n/trunc" "n/floor" "n/ceil"
    "n/round" "n/abs" "n/fixed" "n/min" "n/max" "n/clamp" ">" ">=" "<"
    "<=" "=" "!=" "bs" "bs/to-b" "bs/>" "bs/>=" "bs/<" "bs/<=" "bs/="
    "bs/!=" "str" "s/join" "s/with" "s/repeat" "s/replace" "s/r"
    "s/replace-all" "s/ra" "s/before" "s/after" "s/slice" "s/lpad"
    "s/rpad" "s/count" "s/empty?" "s/escape" "s/dquote" "dq"
    "s/squote" "sq" "s/unquote" "shq" "s/lower" "s/upper" "s/reverse"
    "s/trim" "s/ltrim" "s/rtrim" "s/starts-with?" "s/ends-with?"
    "s/contains?" "s/>" "s/>=" "s/<" "s/<=" "s/=" "s/!=" "csv/join"
    "path/name" "path/stem" "path/ext" "path/dir" "not" "if" "default"
    "and" "or" "reg" "~" "re/replace" "re/r" "re/replace-all" "re/ra"
    "re/with" "re/extract" "re/ex" "date" "d/year" "d/month" "d/day"
    "d/weekday" "d/add" "d/sub" "d/diff" "d/>" "d/>=" "d/<" "d/<="
    "d/=" "d/!=" "dt/unix" "dt/to-unix" "dt/fmt" "dt/now" "dt/floor-s"
    "dt/floor-m" "dt/floor-h" "dt/floor-d" "dt/add" "dt/sub" "dt/diff"
    "du/s" "du/ms" "du/m" "du/h" "du/d" "du/to-ms" "du/to-s" "du/to-m"
    "du/to-h" "du/to-d" "dt/>" "dt/>=" "dt/<" "dt/<=" "dt/=" "dt/!="
    "ip" "ip/expand" "ip/binary" "cidr" "cidr/from-mask"
    "cidr/netmask" "cidr/wildcard" "cidr/host-first" "cidr/host-last"
    "cidr/host-count" "cidr/size-str" "ip/version" "ip/v4?" "ip/v6?"
    "ip/=" "ip/!=" "ip/private?" "ip/loopback?" "ip/link-local?"
    "ip/multicast?" "cidr/contains?" "cidr/network" "cidr/prefix"
    "cidr/first" "cidr/last" "cidr/size" "url/scheme" "url/host"
    "url/port" "url/path" "url/query" "url/fragment" "url/query-get"
    "url/query-has?" "url/encode" "url/decode" "semver/>" "semver/>="
    "semver/<" "semver/<=" "semver/=" "semver/!=" "semver/major"
    "semver/minor" "semver/patch" "semver/prerelease" "semver/build"
    "uuid" "uuid/v4" "uuid/v7" "uuid/version" "uuid/time" "uuid/>"
    "uuid/>=" "uuid/<" "uuid/<=" "uuid/=" "uuid/!=" "ulid" "ulid/new"
    "ulid/time" "ulid/>" "ulid/>=" "ulid/<" "ulid/<=" "ulid/="
    "ulid/!=" "->" "->>")
  "Callable Cho names generated from metadata.")

(defconst cho-mode--eldoc-signatures
  '(("print"
     "(print VALUE:Value ...) — print values separated by spaces")
    ("p" "(p VALUE:Value ...) — print values separated by spaces")
    ("filter" "(filter CONDITION:Boolean) — continue only when true")
    ("f" "(f CONDITION:Boolean) — continue only when true")
    ("field"
     "(field NUMBER:Number) → String — get a field by its computed number")
    ("fields"
     "(fields START:Number END:Number) → String — get a computed inclusive field range")
    ("fields-from"
     "(fields-from START:Number) → String — get fields from a computed position through the record end")
    ("fields-to"
     "(fields-to END:Number) → String — get fields from the record start through a computed position")
    ("+" "(+ LEFT:Number RIGHT:Number) → Number — add")
    ("-" "(- LEFT:Number RIGHT:Number) → Number — subtract")
    ("*" "(* LEFT:Number RIGHT:Number) → Number — multiply")
    ("/" "(/ LEFT:Number RIGHT:Number) → Number — divide")
    ("%" "(% LEFT:Number RIGHT:Number) → Number — remainder")
    ("n/trunc"
     "(n/trunc VALUE:Number) → Number — discard fractional digits toward zero")
    ("n/floor"
     "(n/floor VALUE:Number) → Number — round down toward negative infinity")
    ("n/ceil"
     "(n/ceil VALUE:Number) → Number — round up toward positive infinity")
    ("n/round"
     "(n/round VALUE:Number) → Number — round to nearest, halves away from zero")
    ("n/abs" "(n/abs VALUE:Number) → Number — absolute value")
    ("n/fixed"
     "(n/fixed VALUE:Number DIGITS:Number) → String — format with 0 to 100 fractional digits")
    ("n/min"
     "(n/min NUMBER:Number NUMBER:Number ...) → Number — return the smallest number")
    ("n/max"
     "(n/max NUMBER:Number NUMBER:Number ...) → Number — return the largest number")
    ("n/clamp"
     "(n/clamp VALUE:Number MINIMUM:Number MAXIMUM:Number) → Number — limit a number to an inclusive range")
    (">" "(> LEFT:Number RIGHT:Number) → Boolean — greater than")
    (">="
     "(>= LEFT:Number RIGHT:Number) → Boolean — greater than or equal")
    ("<" "(< LEFT:Number RIGHT:Number) → Boolean — less than")
    ("<="
     "(<= LEFT:Number RIGHT:Number) → Boolean — less than or equal")
    ("=" "(= LEFT:Number RIGHT:Number) → Boolean — equal")
    ("!=" "(!= LEFT:Number RIGHT:Number) → Boolean — not equal")
    ("bs"
     "(bs VALUE:ByteSize) → ByteSize — validate and normalize a byte size")
    ("bs/to-b"
     "(bs/to-b VALUE:ByteSize) → Number — convert a byte size to bytes")
    ("bs/>"
     "(bs/> LEFT:ByteSize RIGHT:ByteSize) → Boolean — greater than")
    ("bs/>="
     "(bs/>= LEFT:ByteSize RIGHT:ByteSize) → Boolean — greater than or equal")
    ("bs/<"
     "(bs/< LEFT:ByteSize RIGHT:ByteSize) → Boolean — less than")
    ("bs/<="
     "(bs/<= LEFT:ByteSize RIGHT:ByteSize) → Boolean — less than or equal")
    ("bs/=" "(bs/= LEFT:ByteSize RIGHT:ByteSize) → Boolean — equal")
    ("bs/!="
     "(bs/!= LEFT:ByteSize RIGHT:ByteSize) → Boolean — not equal")
    ("str" "(str VALUE:Value ...) → String — concatenate values")
    ("s/join"
     "(s/join SEPARATOR:Value VALUE:Value ...) → String — join values")
    ("s/with"
     "(s/with VALUE:Value BODY:Value) → Value — split on whitespace"
     "(s/with VALUE:Value DELIMITER:Value BODY:Value) → Value — split on a literal delimiter")
    ("s/repeat"
     "(s/repeat VALUE:Value COUNT:Number) → String — repeat a value")
    ("s/replace"
     "(s/replace VALUE:Value FROM:Value TO:Value) → String — replace the first literal match")
    ("s/r"
     "(s/r VALUE:Value FROM:Value TO:Value) → String — replace the first literal match")
    ("s/replace-all"
     "(s/replace-all VALUE:Value FROM:Value TO:Value) → String — replace all literal matches")
    ("s/ra"
     "(s/ra VALUE:Value FROM:Value TO:Value) → String — replace all literal matches")
    ("s/before"
     "(s/before VALUE:Value DELIMITER:Value) → String — take text before the first literal delimiter")
    ("s/after"
     "(s/after VALUE:Value DELIMITER:Value) → String — take text after the first literal delimiter")
    ("s/slice"
     "(s/slice VALUE:Value START:Number [LENGTH:Number]) → String — take Unicode characters from a 1-based start")
    ("s/lpad"
     "(s/lpad VALUE:Value WIDTH:Number [FILL:Value]) → String — pad the left side to a Unicode character width")
    ("s/rpad"
     "(s/rpad VALUE:Value WIDTH:Number [FILL:Value]) → String — pad the right side to a Unicode character width")
    ("s/count"
     "(s/count VALUE:Value) → Number — count Unicode characters")
    ("s/empty?"
     "(s/empty? VALUE:Value) → Boolean — test whether a string is empty")
    ("s/escape"
     "(s/escape VALUE:Value) → String — escape tabs, newlines, and backslashes")
    ("s/dquote"
     "(s/dquote VALUE:Value) → String — stringify and wrap in escaped double quotes")
    ("dq"
     "(dq VALUE:Value) → String — stringify and wrap in escaped double quotes")
    ("s/squote"
     "(s/squote VALUE:Value) → String — stringify and wrap in escaped single quotes")
    ("sq"
     "(sq VALUE:Value) → String — stringify and wrap in escaped single quotes")
    ("s/unquote"
     "(s/unquote VALUE:Value) → String — remove matching quotes and decode backslash escapes")
    ("shq"
     "(shq VALUE:Value) → String — stringify and quote as one shell-safe argument")
    ("s/lower" "(s/lower VALUE:Value) → String — lowercase")
    ("s/upper" "(s/upper VALUE:Value) → String — uppercase")
    ("s/reverse"
     "(s/reverse VALUE:Value) → String — reverse Unicode characters")
    ("s/trim"
     "(s/trim VALUE:Value) → String — remove Unicode whitespace from both ends"
     "(s/trim VALUE:Value PREFIX:Value SUFFIX:Value) → String — remove one exact prefix and suffix")
    ("s/ltrim"
     "(s/ltrim VALUE:Value) → String — remove Unicode whitespace from the left"
     "(s/ltrim VALUE:Value PREFIX:Value) → String — remove one exact prefix")
    ("s/rtrim"
     "(s/rtrim VALUE:Value) → String — remove Unicode whitespace from the right"
     "(s/rtrim VALUE:Value SUFFIX:Value) → String — remove one exact suffix")
    ("s/starts-with?"
     "(s/starts-with? VALUE:Value PREFIX:Value) → Boolean — test a prefix")
    ("s/ends-with?"
     "(s/ends-with? VALUE:Value SUFFIX:Value) → Boolean — test a suffix")
    ("s/contains?"
     "(s/contains? VALUE:Value NEEDLE:Value) → Boolean — test a substring")
    ("s/>" "(s/> LEFT:Value RIGHT:Value) → Boolean — greater than")
    ("s/>="
     "(s/>= LEFT:Value RIGHT:Value) → Boolean — greater than or equal")
    ("s/<" "(s/< LEFT:Value RIGHT:Value) → Boolean — less than")
    ("s/<="
     "(s/<= LEFT:Value RIGHT:Value) → Boolean — less than or equal")
    ("s/=" "(s/= LEFT:Value RIGHT:Value) → Boolean — equal")
    ("s/!=" "(s/!= LEFT:Value RIGHT:Value) → Boolean — not equal")
    ("csv/join"
     "(csv/join VALUE:Value ...) → String — join values as one CSV record")
    ("path/name"
     "(path/name VALUE:String) → String — extract the final path component")
    ("path/stem"
     "(path/stem VALUE:String) → String — extract the final component without its extension")
    ("path/ext"
     "(path/ext VALUE:String) → String — extract the extension without its dot or an empty string")
    ("path/dir"
     "(path/dir VALUE:String) → String — extract the directory or an empty string")
    ("not" "(not VALUE:Boolean) → Boolean — negate")
    ("if"
     "(if CONDITION:Boolean THEN:Value ELSE:Value) → Value — select one value lazily")
    ("default"
     "(default VALUE:Value FALLBACK:Value) → Value — use a fallback when the value is empty or errors")
    ("and"
     "(and VALUE:Boolean VALUE:Boolean ...) → Boolean — stop at the first false value")
    ("or"
     "(or VALUE:Boolean VALUE:Boolean ...) → Boolean — stop at the first true value")
    ("reg"
     "(reg PATTERN:Regex) → Boolean — match a regular expression"
     "(reg VALUE:Value PATTERN:Regex) → Boolean — match a regular expression")
    ("~" "(~ PATTERN:Regex) → Boolean — match a regular expression"
     "(~ VALUE:Value PATTERN:Regex) → Boolean — match a regular expression")
    ("re/replace"
     "(re/replace VALUE:Value PATTERN:Regex REPLACEMENT:Value) → String — replace the first regular-expression match")
    ("re/r"
     "(re/r VALUE:Value PATTERN:Regex REPLACEMENT:Value) → String — replace the first regular-expression match")
    ("re/replace-all"
     "(re/replace-all VALUE:Value PATTERN:Regex REPLACEMENT:Value) → String — replace all regular-expression matches")
    ("re/ra"
     "(re/ra VALUE:Value PATTERN:Regex REPLACEMENT:Value) → String — replace all regular-expression matches")
    ("re/with"
     "(re/with VALUE:Value PATTERN:Regex BODY:Value) → Value — evaluate a value using fields split by a regular expression")
    ("re/extract"
     "(re/extract VALUE:Value PATTERN:Regex [GROUP:Number]) → String — extract the first match or a numbered capture")
    ("re/ex"
     "(re/ex VALUE:Value PATTERN:Regex [GROUP:Number]) → String — extract the first match or a numbered capture")
    ("date" "(date VALUE:Date) → Date — validate a calendar date")
    ("d/year" "(d/year DATE:Date) → Number — extract the year")
    ("d/month"
     "(d/month DATE:Date) → Number — extract the month number")
    ("d/day"
     "(d/day DATE:Date) → Number — extract the day of the month")
    ("d/weekday"
     "(d/weekday DATE:Date) → Number — extract the ISO weekday number")
    ("d/add"
     "(d/add DATE:Date DAYS:Number) → Date — add whole calendar days")
    ("d/sub"
     "(d/sub DATE:Date DAYS:Number) → Date — subtract whole calendar days")
    ("d/diff"
     "(d/diff LEFT:Date RIGHT:Date) → Number — difference in calendar days")
    ("d/>" "(d/> LEFT:Date RIGHT:Date) → Boolean — later than")
    ("d/>="
     "(d/>= LEFT:Date RIGHT:Date) → Boolean — later than or equal")
    ("d/<" "(d/< LEFT:Date RIGHT:Date) → Boolean — earlier than")
    ("d/<="
     "(d/<= LEFT:Date RIGHT:Date) → Boolean — earlier than or equal")
    ("d/=" "(d/= LEFT:Date RIGHT:Date) → Boolean — equal")
    ("d/!=" "(d/!= LEFT:Date RIGHT:Date) → Boolean — not equal")
    ("dt/unix"
     "(dt/unix VALUE:Number) → DateTime — convert Unix seconds")
    ("dt/to-unix"
     "(dt/to-unix DATETIME:DateTime) → Number — convert a datetime to Unix seconds")
    ("dt/fmt"
     "(dt/fmt DATETIME:DateTime FORMAT:String) → String — format in UTC"
     "(dt/fmt DATETIME:DateTime FORMAT:String TIMEZONE:String) → String — format in the specified timezone")
    ("dt/now"
     "(dt/now) → DateTime — current UTC time at second precision")
    ("dt/floor-s"
     "(dt/floor-s DATETIME:DateTime) → DateTime — floor to a local or UTC second"
     "(dt/floor-s DATETIME:DateTime TIMEZONE:String) → DateTime — floor to a local or UTC second")
    ("dt/floor-m"
     "(dt/floor-m DATETIME:DateTime) → DateTime — floor to a local or UTC minute"
     "(dt/floor-m DATETIME:DateTime TIMEZONE:String) → DateTime — floor to a local or UTC minute")
    ("dt/floor-h"
     "(dt/floor-h DATETIME:DateTime) → DateTime — floor to a local or UTC hour"
     "(dt/floor-h DATETIME:DateTime TIMEZONE:String) → DateTime — floor to a local or UTC hour")
    ("dt/floor-d"
     "(dt/floor-d DATETIME:DateTime) → DateTime — floor to a local or UTC calendar day"
     "(dt/floor-d DATETIME:DateTime TIMEZONE:String) → DateTime — floor to a local or UTC calendar day")
    ("dt/add"
     "(dt/add DATETIME:DateTime DURATION:Duration) → DateTime — add a duration")
    ("dt/sub"
     "(dt/sub DATETIME:DateTime DURATION:Duration) → DateTime — subtract a duration")
    ("dt/diff"
     "(dt/diff LEFT:DateTime RIGHT:DateTime) → Duration — subtract the right datetime from the left")
    ("du/s"
     "(du/s VALUE:Number) → Duration — convert seconds to a duration")
    ("du/ms"
     "(du/ms VALUE:Number) → Duration — convert milliseconds to a duration")
    ("du/m"
     "(du/m VALUE:Number) → Duration — convert minutes to a duration")
    ("du/h"
     "(du/h VALUE:Number) → Duration — convert hours to a duration")
    ("du/d"
     "(du/d VALUE:Number) → Duration — convert fixed 24-hour days to a duration")
    ("du/to-ms"
     "(du/to-ms VALUE:Duration) → Number — convert a duration to milliseconds")
    ("du/to-s"
     "(du/to-s VALUE:Duration) → Number — convert a duration to seconds")
    ("du/to-m"
     "(du/to-m VALUE:Duration) → Number — convert a duration to minutes")
    ("du/to-h"
     "(du/to-h VALUE:Duration) → Number — convert a duration to hours")
    ("du/to-d"
     "(du/to-d VALUE:Duration) → Number — convert a duration to fixed 24-hour days")
    ("dt/>"
     "(dt/> LEFT:DateTime RIGHT:DateTime) → Boolean — greater than")
    ("dt/>="
     "(dt/>= LEFT:DateTime RIGHT:DateTime) → Boolean — greater than or equal")
    ("dt/<"
     "(dt/< LEFT:DateTime RIGHT:DateTime) → Boolean — less than")
    ("dt/<="
     "(dt/<= LEFT:DateTime RIGHT:DateTime) → Boolean — less than or equal")
    ("dt/=" "(dt/= LEFT:DateTime RIGHT:DateTime) → Boolean — equal")
    ("dt/!="
     "(dt/!= LEFT:DateTime RIGHT:DateTime) → Boolean — not equal")
    ("ip"
     "(ip VALUE:IpAddr) → IpAddr — validate and normalize an IP address")
    ("ip/expand"
     "(ip/expand VALUE:IpAddr) → String — return the full IP address as a string")
    ("ip/binary"
     "(ip/binary VALUE:IpAddr) → String — return the address bits as a string")
    ("cidr"
     "(cidr VALUE:Cidr) → Cidr — create a CIDR normalized to its network address"
     "(cidr IP:IpAddr PREFIX:Number) → Cidr — create a CIDR normalized to its network address")
    ("cidr/from-mask"
     "(cidr/from-mask IP:IpAddr MASK:IpAddr) → Cidr — create a CIDR from an IP address and netmask")
    ("cidr/netmask"
     "(cidr/netmask VALUE:Cidr) → IpAddr — return the network mask")
    ("cidr/wildcard"
     "(cidr/wildcard VALUE:Cidr) → IpAddr — return the inverse network mask")
    ("cidr/host-first"
     "(cidr/host-first VALUE:Cidr) → IpAddr — return the first host address")
    ("cidr/host-last"
     "(cidr/host-last VALUE:Cidr) → IpAddr — return the last host address")
    ("cidr/host-count"
     "(cidr/host-count VALUE:Cidr) → String — return the exact host count as a decimal string")
    ("cidr/size-str"
     "(cidr/size-str VALUE:Cidr) → String — return the exact address count as a decimal string")
    ("ip/version" "(ip/version VALUE:IpAddr) → Number — return 4 or 6")
    ("ip/v4?" "(ip/v4? VALUE:IpAddr) → Boolean — test an IPv4 address")
    ("ip/v6?" "(ip/v6? VALUE:IpAddr) → Boolean — test an IPv6 address")
    ("ip/="
     "(ip/= LEFT:IpAddr RIGHT:IpAddr) → Boolean — test IP address equality")
    ("ip/!="
     "(ip/!= LEFT:IpAddr RIGHT:IpAddr) → Boolean — test IP address inequality")
    ("ip/private?"
     "(ip/private? VALUE:IpAddr) → Boolean — test RFC 1918 IPv4 or fc00::/7 IPv6 ULA")
    ("ip/loopback?"
     "(ip/loopback? VALUE:IpAddr) → Boolean — test a loopback address")
    ("ip/link-local?"
     "(ip/link-local? VALUE:IpAddr) → Boolean — test a link-local address")
    ("ip/multicast?"
     "(ip/multicast? VALUE:IpAddr) → Boolean — test a multicast address")
    ("cidr/contains?"
     "(cidr/contains? CIDR:Cidr IP:IpAddr) → Boolean — test CIDR membership")
    ("cidr/network"
     "(cidr/network VALUE:Cidr) → IpAddr — return the network address")
    ("cidr/prefix"
     "(cidr/prefix VALUE:Cidr) → Number — return the prefix length")
    ("cidr/first"
     "(cidr/first VALUE:Cidr) → IpAddr — return the lowest address")
    ("cidr/last"
     "(cidr/last VALUE:Cidr) → IpAddr — return the highest address")
    ("cidr/size"
     "(cidr/size VALUE:Cidr) → Number — return the address count up to 2^53 - 1")
    ("url/scheme"
     "(url/scheme VALUE:Url) → String — extract the scheme")
    ("url/host" "(url/host VALUE:Url) → String — extract the host")
    ("url/port"
     "(url/port VALUE:Url) → String — extract the port or an empty string")
    ("url/path" "(url/path VALUE:Url) → String — extract the path")
    ("url/query"
     "(url/query VALUE:Url) → String — extract the query or an empty string")
    ("url/fragment"
     "(url/fragment VALUE:Url) → String — extract the fragment or an empty string")
    ("url/query-get"
     "(url/query-get URL:Url NAME:String) → String — return the first decoded value or an empty string")
    ("url/query-has?"
     "(url/query-has? URL:Url NAME:String) → Boolean — test whether a decoded query name exists")
    ("url/encode"
     "(url/encode VALUE:String) → String — encode an RFC 3986 component")
    ("url/decode"
     "(url/decode VALUE:String) → String — percent-decode a component")
    ("semver/>"
     "(semver/> LEFT:SemVer RIGHT:SemVer) → Boolean — greater than")
    ("semver/>="
     "(semver/>= LEFT:SemVer RIGHT:SemVer) → Boolean — greater than or equal")
    ("semver/<"
     "(semver/< LEFT:SemVer RIGHT:SemVer) → Boolean — less than")
    ("semver/<="
     "(semver/<= LEFT:SemVer RIGHT:SemVer) → Boolean — less than or equal")
    ("semver/="
     "(semver/= LEFT:SemVer RIGHT:SemVer) → Boolean — equal")
    ("semver/!="
     "(semver/!= LEFT:SemVer RIGHT:SemVer) → Boolean — not equal")
    ("semver/major"
     "(semver/major VALUE:SemVer) → Number — return the major version")
    ("semver/minor"
     "(semver/minor VALUE:SemVer) → Number — return the minor version")
    ("semver/patch"
     "(semver/patch VALUE:SemVer) → Number — return the patch version")
    ("semver/prerelease"
     "(semver/prerelease VALUE:SemVer) → String — return prerelease text or an empty string")
    ("semver/build"
     "(semver/build VALUE:SemVer) → String — return build metadata or an empty string")
    ("uuid" "(uuid VALUE:Uuid) → Uuid — validate and normalize a UUID")
    ("uuid/v4" "(uuid/v4) → Uuid — generate a random UUID version 4")
    ("uuid/v7"
     "(uuid/v7) → Uuid — generate a time-ordered UUID version 7")
    ("uuid/version"
     "(uuid/version VALUE:Uuid) → Number — return the UUID version number")
    ("uuid/time"
     "(uuid/time VALUE:Uuid) → DateTime — extract the timestamp from a UUID")
    ("uuid/>" "(uuid/> LEFT:Uuid RIGHT:Uuid) → Boolean — greater than")
    ("uuid/>="
     "(uuid/>= LEFT:Uuid RIGHT:Uuid) → Boolean — greater than or equal")
    ("uuid/<" "(uuid/< LEFT:Uuid RIGHT:Uuid) → Boolean — less than")
    ("uuid/<="
     "(uuid/<= LEFT:Uuid RIGHT:Uuid) → Boolean — less than or equal")
    ("uuid/=" "(uuid/= LEFT:Uuid RIGHT:Uuid) → Boolean — equal")
    ("uuid/!=" "(uuid/!= LEFT:Uuid RIGHT:Uuid) → Boolean — not equal")
    ("ulid" "(ulid VALUE:Ulid) → Ulid — validate and normalize a ULID")
    ("ulid/new" "(ulid/new) → Ulid — generate a monotonic ULID")
    ("ulid/time"
     "(ulid/time VALUE:Ulid) → DateTime — extract the timestamp from a ULID")
    ("ulid/>" "(ulid/> LEFT:Ulid RIGHT:Ulid) → Boolean — greater than")
    ("ulid/>="
     "(ulid/>= LEFT:Ulid RIGHT:Ulid) → Boolean — greater than or equal")
    ("ulid/<" "(ulid/< LEFT:Ulid RIGHT:Ulid) → Boolean — less than")
    ("ulid/<="
     "(ulid/<= LEFT:Ulid RIGHT:Ulid) → Boolean — less than or equal")
    ("ulid/=" "(ulid/= LEFT:Ulid RIGHT:Ulid) → Boolean — equal")
    ("ulid/!=" "(ulid/!= LEFT:Ulid RIGHT:Ulid) → Boolean — not equal")
    ("->"
     "(-> VALUE:Value STEP:Step ...) → Value — insert a value as each step's first argument")
    ("->>"
     "(->> VALUE:Value STEP:Step ...) → Value — insert a value as each step's last argument"))
  "Cho signatures generated from metadata.")

(provide 'cho-mode-data)
;;; cho-mode-data.el ends here
