;;; generate-cho-mode-data.el --- Generate Cho mode data from metadata -*- lexical-binding: t; -*-

(require 'json)
(require 'subr-x)

(defconst cho-mode-generator--directory
  (file-name-directory (or load-file-name buffer-file-name)))

(defconst cho-mode-generator--metadata-file
  (expand-file-name "../../metadata.json" cho-mode-generator--directory))

(defun cho-mode-generator--parameter (parameter)
  "Render metadata PARAMETER as an Eldoc parameter."
  (let* ((name (upcase (alist-get 'name parameter)))
         (type (alist-get 'type parameter))
         (label (if (and type (not (string-empty-p type)))
                    (format "%s:%s" name type)
                  name)))
    (pcase (alist-get 'cardinality parameter)
      ("required" label)
      ("optional" (format "[%s]" label))
      ("zero_or_more" (format "%s ..." label))
      ("one_or_more" (format "%s %s ..." label label))
      (cardinality (error "Unknown Cho parameter cardinality: %S" cardinality)))))

(defun cho-mode-generator--signature (name signature summary)
  "Render a metadata SIGNATURE for NAME, followed by SUMMARY."
  (let* ((parameters (mapcar #'cho-mode-generator--parameter
                             (alist-get 'parameters signature)))
         (returns (alist-get 'returns signature))
         (description (or (alist-get 'summary signature) summary))
         (text (format "(%s%s)%s"
                       name
                       (if parameters (concat " " (string-join parameters " ")) "")
                       (if returns (format " → %s" returns) ""))))
    (if (and description (not (string-empty-p description)))
        (format "%s — %s" text description)
      text)))

(defun cho-mode-generator--entries (metadata)
  "Return generated Eldoc entries from parsed METADATA."
  (apply
   #'append
   (mapcar
    (lambda (callable)
      (let ((names (cons (alist-get 'name callable)
                         (alist-get 'aliases callable)))
            (signatures (alist-get 'signatures callable))
            (summary (alist-get 'summary callable)))
        (mapcar
         (lambda (name)
           (cons name
                 (mapcar (lambda (signature)
                           (cho-mode-generator--signature name signature summary))
                         signatures)))
         names)))
    (alist-get 'callables metadata))))

;;;###autoload
(defun cho-mode-generate-data (&optional metadata-file output-file)
  "Generate Cho mode data from METADATA-FILE into OUTPUT-FILE.

Defaults to metadata.json in the repository root and cho-mode-data.el next
to this file.  `cho-mode' only loads the checked-in output file."
  (interactive)
  (let* ((metadata-file (expand-file-name
                         (or metadata-file cho-mode-generator--metadata-file)))
         (output-file (expand-file-name
                       (or output-file "cho-mode-data.el")
                       cho-mode-generator--directory))
         (metadata
          (with-temp-buffer
            (insert-file-contents metadata-file)
            (json-parse-buffer :object-type 'alist :array-type 'list
                               :null-object nil :false-object nil)))
         (schema-version (alist-get 'schema_version metadata))
         (cho-version (alist-get 'cho_version metadata))
         (entries (cho-mode-generator--entries metadata))
         (functions (mapcar #'car entries)))
    (unless (= schema-version 1)
      (error "Unsupported Cho metadata schema version: %S" schema-version))
    (with-temp-file output-file
      (insert ";;; cho-mode-data.el --- Generated Cho callable data -*- lexical-binding: t; -*-\n"
              ";; Generated from metadata.json by generate-cho-mode-data.el.\n"
              ";; Do not edit this file by hand.\n\n")
      (pp `(defconst cho-mode--metadata-version ,cho-version
             "Cho version represented by the generated mode data.")
          (current-buffer))
      (insert "\n")
      (pp `(defconst cho-mode--functions ',functions
             "Callable Cho names generated from metadata.")
          (current-buffer))
      (insert "\n")
      (pp `(defconst cho-mode--eldoc-signatures ',entries
             "Cho signatures generated from metadata.")
          (current-buffer))
      (insert "\n(provide 'cho-mode-data)\n"
              ";;; cho-mode-data.el ends here\n"))
    (when (called-interactively-p 'interactive)
      (message "Generated %s (%d callables, Cho %s)"
               output-file (length entries) cho-version))))

(provide 'generate-cho-mode-data)
;;; generate-cho-mode-data.el ends here
